### ISSUE TITLE
使用文档

### ISSUE THREAD

**Issue by nnianhouss** [jackleemeta/al_downloader_flutter#1]
能否加上使用文档跟demo，下载源码好像没有demo

**Comment by jackleemeta** [comment]
> 能否加上使用文档跟demo，下载源码好像没有demo

https://github.com/jackleemeta/al_downloader_flutter

Demo: 
https://github.com/jackleemeta/al_downloader_flutter/blob/master/al_downloader/example/lib/main.dart
https://github.com/jackleemeta/al_downloader_flutter/blob/master/al_downloader/example/ios/Runner/AppDelegate.swift
https://github.com/jackleemeta/al_downloader_flutter/blob/master/al_downloader/example/ios/Runner/Info.plist
