### ISSUE TITLE
Is it compatible with ios16?

### ISSUE THREAD

**Issue by aiqianqianli** [jackleemeta/al_downloader_flutter#10]
xcode 14 will compile error

**Comment by aiqianqianli** [comment]
flutter run release打出的包，会导致下载进度没法显示，flutter run一切正常

**Comment by aiqianqianli** [comment]
release包抓到的日志
![1381663115308_ pic](https://user-images.githubusercontent.com/16432852/190032728-5e39c879-8036-4124-8140-1d9594ac26e1.jpg)
环境是
![1391663115522_ pic](https://user-images.githubusercontent.com/16432852/190032752-2474540d-a2be-422e-b846-6c67feef6d58.jpg)

**Comment by jackleemeta** [comment]
> flutter run release打出的包，会导致下载进度没法显示，flutter run一切正常

你好，最近有些忙，没能及时回复

可以确定的是这个问题是Flutter SDK 3.3.0之后出现的。可能是SDK使用机制有变，也可能是Flutter SDK 3.3.0本身的错误。

**Comment by aiqianqianli** [comment]
thanks @jackleemeta

**Comment by jackleemeta** [comment]
> flutter run release打出的包，会导致下载进度没法显示，flutter run一切正常

你好，问题已经修复，升级al_downloader到1.5.9版本后可以在Flutter SDK 3.3.2 下使用了。

**Comment by jackleemeta** [comment]
> xcode 14 will compile error

这个问题是Xcode14 beta和Xcode14引入的，后续apple应该会修复；问题详情和临时解决方案如下：

resource bundle编译问题：
1. CODE_SIGNING_ALLOWED默认值改变问题
2. TEAM_ID继承失败问题

解决方案参考：
1. https://developer.apple.com/forums/thread/708659
2. https://stackoverflow.com/questions/72561696/xcode-14-needs-selected-development-team-for-pod-bundles
3. https://github.com/facebook/react-native/issues/34673

**Comment by gauchok** [comment]
I have a question, where are the downloaded files saved?

**Comment by jackleemeta** [comment]
> I have a question, where are the downloaded files saved in iOS?

@gauchok, Like this.

```
final model = await ALDownloaderPersistentFileManager
    .lazyGetALDownloaderPathModelForUrl(url);
debugPrint(
    "ALDownloader | get 'physical directory path' and 'virtual/physical file name' of the file for [url], url = $url, model = $model\n");
```
