### ISSUE TITLE
ALDownloader | try to download url, but the url is enqueued

### ISSUE THREAD

**Issue by GaoWhitebird** [jackleemeta/al_downloader_flutter#11]
ALDownloader.addForeverDownloaderHandlerInterface(
            ALDownloaderHandlerInterface(progressHandler: (progress) {
            }, succeededHandler: () {
            }, failedHandler: () {
              hideLoading();
            }, pausedHandler: () {
            }),
            url);

await ALDownloader.download(url,); 

ALDownloader | try to download url, but the url is enqueued, url = ..., taskId = 1601dcc0-42f3-48e1-824a-eedba8cdaf7f

I am trying to download file from url but it is showing this again and again in log.
File is downloaded already and it is showing above message.
But I didn't catch any callback or log till file is downloaded.
How can I get status and control them ?
Thanks.

**Comment by jackleemeta** [comment]
Hi @GaoWhitebird, please provide the following info.

1. al_downloader version
2. flutter mode
3. platform and platform version
4. the operating path of the recurrence. For example that process exits when downloading.

Thanks.

**Comment by hycinth** [comment]
i have the same problem 
Flutter 3.3.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision e3c29ec00c (8 weeks ago) • 2022-09-14 08:46:55 -0500
Engine • revision a4ff2c53d8
Tools • Dart 2.18.1 • DevTools 2.15.0
and al_downloader: ^1.6.1

**Comment by jackleemeta** [comment]
> i have the same problem
> Flutter 3.3.2 • channel stable • https://github.com/flutter/flutter.git
> Framework • revision e3c29ec00c (8 weeks ago) • 2022-09-14 08:46:55 -0500
> Engine • revision a4ff2c53d8
> Tools • Dart 2.18.1 • DevTools 2.15.0
> and al_downloader: ^1.6.1

Hi @hycinth , please provide the following info to help resolving this issue.

1. Flutter mode (debug/profile/release)
2. Device (e.g. iPhone14Pro Simulator / iPhone14Pro Physical Device / Android Pixel XL API 31 Emulator / Android Pixel XL API 31 Physical Device)
3. OS Version (e.g. iOS 16 / Android 11)
4. The operating path of the recurrence. For example that process exits when downloading. (If it could reproduce.)

Thanks.
