### ISSUE TITLE
Example app not working

### ISSUE THREAD

**Issue by al-virti** [jackleemeta/al_downloader_flutter#12]
Hello, when I try to run the example app, all downloads immediately fail? I load up the app and all of the download tasks fail instantly. When I press the remove button then download, they also fail instantly.

More details:
* ALDownloader 1.5.9
* Flutter mode: release (working in debug)
* Android 13 on Pixel 4 XL

[aldownloader_log.txt](https://github.com/jackleemeta/al_downloader_flutter/files/9774943/aldownloader_log.txt)

I tried the example app in flutter_downloader and downloads are working in release mode.

**Comment by jackleemeta** [comment]
Hi @al-virti , thanks for ur issue.

It does indeed have the problem, and it's been fixed, please pull the latest code and use the latest version.

**Comment by al-virti** [comment]
All working great, thank you very much for the swift response!
