### ISSUE TITLE
download support chineses

### ISSUE THREAD

**Issue by aiqianqianli** [jackleemeta/al_downloader_flutter#14]
Does the downloaded link support Chinese strings?

**Comment by aiqianqianli** [comment]
<img width="1695" alt="WeChate3200f8f95db6cb9b1eb9dc2306a4dcb" src="https://user-images.githubusercontent.com/16432852/199194062-a69d4ba9-d36a-494e-8f98-a0af0bd3f07b.png">

**Comment by jackleemeta** [comment]
> Does the downloaded link support Chinese strings?

框架不会转义url，做下urlEncode再发请求
