### ISSUE TITLE
测试了一下example上的代码，暂停之后，退出app，点击下载，进度条不动，但是下载任务在跑

### ISSUE THREAD

**Issue by smin9** [jackleemeta/al_downloader_flutter#16]
flutter 3.0  android 11

**Comment by jackleemeta** [comment]
> flutter 3.0 android 11

信息再详细些哈。

精确的FlutterSdk版本和al_downloader版本
Flutter mode
真机or模拟器
是否是必现

**Comment by smin9** [comment]
Flutter 3.0.5 
al_downloader  1.6.2
真机：小米9 android 11
必现
操作步骤：
1、点击下载
2、暂停
3 、杀死app
4、重新打开app，点击下载
5、进度条不更新

**Comment by jackleemeta** [comment]
@smin9 , 我这暂时重现不了。

你那边flutter sdk 升级到最新版，然后debug下这部分代码，看看具体哪出问题了造成没有进度回调？
[flutterdownloader](https://github.com/fluttercommunity/flutter_downloader/tree/master/android/src/main/kotlin/vn/hunghd/flutterdownloader)

**Comment by jackleemeta** [comment]
@smin9 是al_downloader的问题，可升级到最新版v1.6.6解决这个问题。
