### ISSUE TITLE
ALDownloader.download 回调未执行 

### ISSUE THREAD

**Issue by qq1440214507** [jackleemeta/al_downloader_flutter#18]
如上    progressHandler: (double progress) {
              print(progress);
            }, 执行一次，打印0.0就结束了，flutter 3.7

**Comment by Passer-by** [comment]
https://github.com/jackleemeta/al_downloader_flutter/blob/master/lib/src/ALDownloaderBatcher.dart#L108 我看这段代码感觉怪怪的

**Comment by Passer-by** [comment]
这里是单个文件下载完成后再算整体的进度吗

**Comment by qq1440214507** [comment]
await ALDownloader.download(playUrl,downloaderHandlerInterface:ALDownloaderHandlerInterface(
            failedHandler: () {
             
            },
            succeededHandler: () async {
           
            }));
就是比如这段代码 回调都没有执行 是不是用法不对 确实是下载完成了

**Comment by jackleemeta** [comment]
> 这里是单个文件下载完成后再算整体的进度吗

是的

https://github.com/jackleemeta/al_downloader_flutter/blob/9f8d322e0a802874793b825c81d58afeda24cdd6/lib/src/ALDownloaderBatcher.dart#L11

**Comment by Passer-by** [comment]
哎，那就没什么问题了。

**Comment by jackleemeta** [comment]
> ```
> await ALDownloader.download(playUrl,downloaderHandlerInterface:ALDownloaderHandlerInterface(
>         failedHandler: () {
>          
>         },
>         succeededHandler: () async {
>        
>         }));
> ```
> 
> 
>      
>   
> 
> 就是比如这段代码 回调都没有执行 是不是用法不对 确实是下载完成了

正在修哈，稍后发个版本

**Comment by qq1440214507** [comment]
> 

好的

**Comment by Passer-by** [comment]
批量下载是不是也有上面这个问题 我现在也收不到

**Comment by Passer-by** [comment]
emmm。按逻辑上来看好像是这样

**Comment by jackleemeta** [comment]
> 批量下载是不是也有上面这个问题 我现在也收不到

对，一个问题。批量下载也要走单下载。

**Comment by jackleemeta** [comment]
@qq1440214507 @Passer-by 

可以update到1.6.8了

**Comment by Passer-by** [comment]
可以收到回调了 : )
