### ISSUE TITLE
下载路径和文件名可以作为参数传过来吗？

### ISSUE THREAD

**Issue by ShiChenZhi** [jackleemeta/al_downloader_flutter#19]
如果下载oss处理过的url，没有固定后缀名

**Comment by ShiChenZhi** [comment]
我已经直接修改了源码，但害怕时间久了更新了依赖而忘记修改

**Comment by jackleemeta** [comment]
你好，感谢你的建议

后缀的问题我这边看下哈，要考量下要不要改。因为有没有后缀其实都不影响二进制文件的加载，比如[Image.file]

后续要修改的话应该也是不支持手动传入后缀的，从逻辑上看我觉得这是没必要并且可能出错的，可能会通过解析`response的content-type`或者`二进制文件的格式字节段`来确定准确扩展名

目前，如果是为了文件名等显示需要，建议在业务里url和文件名等做映射
