### ISSUE TITLE
空安全问题

### ISSUE THREAD

**Issue by 1011382654** [jackleemeta/al_downloader_flutter#2]
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:al_downloader

For solutions, see https://dart.dev/go/unsound-null-safety

**Comment by jackleemeta** [comment]
> Error: Cannot run with sound null safety, because the following dependencies don't support null safety:
> 
> * package:al_downloader
> 
> For solutions, see https://dart.dev/go/unsound-null-safety

你好，稍后会对null safety适配，再等一等。

**Comment by jackleemeta** [comment]
> 

https://pub.dev/packages/al_downloader

**Comment by jackleemeta** [comment]
> Error: Cannot run with sound null safety, because the following dependencies don't support null safety:
> 
> * package:al_downloader
> 
> For solutions, see https://dart.dev/go/unsound-null-safety

https://pub.dev/packages/al_downloader

**Comment by 1011382654** [comment]
很好用，感谢大佬
