### ISSUE TITLE
Unhandled Exception: Bad state: Stream has already been listened to.

### ISSUE THREAD

**Issue by qq1440214507** [jackleemeta/al_downloader_flutter#20]
Unhandled Exception: Bad state: Stream has already been listened to.
E/flutter (17234): #0      _StreamController._subscribe (dart:async/stream_controller.dart:676:7)
E/flutter (17234): #1      _ControllerStream._createSubscription (dart:async/stream_controller.dart:827:19)
E/flutter (17234): #2      _StreamImpl.listen (dart:async/stream_impl.dart:471:9)
E/flutter (17234): #3      _ReceivePortImpl.listen (dart:isolate-patch/isolate_patch.dart:92:31)
E/flutter (17234): #4      ALDownloader._addIsolateNameServerPortService (package:al_downloader/src/ALDownloader.dart:470:18)
E/flutter (17234): #5      ALDownloader.initialize (package:al_downloader/src/ALDownloader.dart:21:7)
E/flutter (17234): <asynchronous suspension>
E/flutter (17234): #6      ALDownloader.download (package:al_downloader/src/ALDownloader.dart:54:5)
E/flutter (17234): <asynchronous suspension>

**Comment by jackleemeta** [comment]
单独调用下[ALDownloader.initialize]，时机早一点，比如在main方法里

**Comment by qq1440214507** [comment]
haode
