### ISSUE TITLE
如果批量下载数量太大，暂停后恢复耗时会很久

### ISSUE THREAD

**Issue by Passer-by** [jackleemeta/al_downloader_flutter#21]
比如我创建了 一个 1000个url的批量下载任务，首次下载没问题，但是如果暂停后立即恢复，需要等待很长时间。

**Comment by jackleemeta** [comment]
> 比如我创建了 一个 1000个url的批量下载任务，首次下载没问题，但是如果暂停后立即恢复，需要等待很长时间。

具体时长多少？iOS和Android都很久？

**Comment by Passer-by** [comment]
> 

目前在安卓上来看 要个10秒。iOS我今晚回去看看

**Comment by Passer-by** [comment]
> > 
> 
> 目前在安卓上来看 要个10秒。iOS我今晚回去看看

需要我提供demo吗

**Comment by jackleemeta** [comment]
> > 目前在安卓上来看 要个10秒。iOS我今晚回去看看
> 
> 需要我提供demo吗

好的 贴一下

**Comment by Passer-by** [comment]
https://github.com/Passer-by/al_downloader_flutter 用的是你的demo。增加了批量下载的数量

**Comment by Passer-by** [comment]
或许这不是al_downloader的问题 https://github.com/fluttercommunity/flutter_downloader/issues/733  应该是 flutter_downloader的

**Comment by jackleemeta** [comment]
> 或许这不是al_downloader的问题 [fluttercommunity/flutter_downloader#733](https://github.com/fluttercommunity/flutter_downloader/issues/733) 应该是 flutter_downloader的

两边都有一些问题，我这边正在修复，要花点时间。

**Comment by Passer-by** [comment]
> > 或许这不是al_downloader的问题 [fluttercommunity/flutter_downloader#733](https://github.com/fluttercommunity/flutter_downloader/issues/733) 应该是 flutter_downloader的
> 
> 两边都有一些问题，我这边正在修复，要花点时间。

我想了想，既然一口气添加太多任务会导致重新开始慢。al_download是否可以通过 分开添加任务来达到批量下载的效果。这样问题就变成了如何管理好下载中和下载完以及等待下载的状态了

**Comment by jackleemeta** [comment]
@Passer-by 谢谢建议哈，分批加载其实效用有限，最终还是要走入串行环境（下面会提到）；我这边在iOS下做了下调试，android没看，但是本质策略应该都差不多

## 我的调试环境：

Flutter mode: release
平台：iOS
设备：iPhone12真机
系统：iOS16.3

## 数据

任务数：1000个任务
总耗时：14979ms
单任务耗时：14.98ms = 14979ms / 1000

- [FlutterDownloader.enqueue]耗时：

![checkondart](https://user-images.githubusercontent.com/66350348/217767011-2b5a65bc-00d9-47e2-9ae7-d5ec87959798.png)

- [downloadTaskWithRequest:]耗时：
![checkonios](https://user-images.githubusercontent.com/66350348/217766774-f1992855-afbe-4d45-af55-4dd50e96228a.png)

可以看到FlutterDownloader.enqueue]整个调用链耗时集中到原生方法[downloadTaskWithRequest:]

## 耗时原因：

1. [FlutterDownloader.enqueue]方法耗时久，更具体一点，[downloadTaskWithRequest:]耗时久;[FlutterDownloader.enqueue]最终会调用至[downloadTaskWithRequest:]
https://github.com/fluttercommunity/flutter_downloader/blob/8b7ac158f38b4708f6ae38e234df51fb21dfdd61/ios/Classes/FlutterDownloaderPlugin.m#L178
2. al_downloader未做事件优先级管理

## 解决方案

1. al_downloader做事件优先级管理；例如暂停时，会先忽略队列任务；`先做这个，这个做完基本解决问题`
2. FlutterDownloader的[downloadTaskWithRequest:]改造，例如多队列或者换方法

## 大量数据下其他问题和解决方案

问题：大量数据下，也发现了事件交叉引起的问题
解决方案：al_downloader使用队列管理事件

## 其他

Flutter mode = Debug时，测试数据参考意义不大，1000个任务可能会耗时50000毫秒，和release相差甚远

**Comment by jackleemeta** [comment]
上述问题在v1.7.1中已基本解决。

同时，应用到了你提到的批处理方式，非常感谢你的想法 @Passer-by

**Comment by Passer-by** [comment]
> 上述问题在v1.7.1中已基本解决。
> 
> 同时，应用到了你提到的批处理方式，非常感谢你的想法 @Passer-by

辛苦了，但正如你之前所说，批处理效果确实也是有限（我自己稍微试了一下）只能说基于flutter_downloader局限性太大，这种处理其实都应该放置在native那边。

**Comment by jackleemeta** [comment]
> 

理想化的flutter_downloader，应该是对海量任务主线程非阻塞、队列化、可靠并充分回执的，但目前它这些缺失还有很多。对flutter_downloader补充功能和屏蔽修复缺陷，这也是al_downloader的意义之一。
