### ISSUE TITLE
m3u8 dowaload

### ISSUE THREAD

**Issue by ShareZore** [jackleemeta/al_downloader_flutter#28]
Can you support m3u8 download?

**Comment by jackleemeta** [comment]
你好，m3u8可以下的阿。

是遇到了什么问题吗？可以贴下详细的信息和日志。

**Comment by jackleemeta** [comment]
或者你的意思是把m3u8文本解析后下载里面的片段吗？这个是不支持的，这是个通用下载器，不会去解析次级资源。

有些类似这个 issue https://github.com/jackleemeta/al_downloader_flutter/issues/8

**Comment by ShareZore** [comment]
Thank you for your answer
