### ISSUE TITLE
请问如何获取全部正在下载中的任务 想做下载器列表

### ISSUE THREAD

**Issue by ZhangZhiH** [jackleemeta/al_downloader_flutter#29]
请问如何获取全部正在下载中的任务 想做下载器列表

**Comment by jackleemeta** [comment]
https://github.com/jackleemeta/al_downloader_flutter/blob/eadfbe309b4d19962b581b3d1f8b7d0b832c69e8/lib/src/ALDownloader.dart#L145

**Comment by ZhangZhiH** [comment]
> https://github.com/jackleemeta/al_downloader_flutter/blob/eadfbe309b4d19962b581b3d1f8b7d0b832c69e8/lib/src/ALDownloader.dart#L145
这个不对 我想要的是 在不知道URL的情况下 我想查询有多少正在下载中的列表 这里并没有这个接口
封装的太死了 原先人家的方法都封装没了我想要的是 FlutterDownloader.loadTasks 以及FlutterDownloader.loadTasksWithRawQuery

**Comment by jackleemeta** [comment]
v1.7.9，task已暴露
