### ISSUE TITLE
下载文件时，可以定义保存的文件名吗

### ISSUE THREAD

**Issue by liuyun1314** [jackleemeta/al_downloader_flutter#3]
如果有怎么操作

**Comment by jackleemeta** [comment]
> 

不支持的，建议在外部文件名和url做映射

**Comment by jackleemeta** [comment]
> 这个问题我也想问下 怎么在外部文件名和url做映射？目前下载了之后，文件名会被md5了，就是下载成功后，我的文件叫什么名字了

在外部维护一张映射表，这张表可以放在内存或者磁盘，url1=name1，url2=name2

**Comment by jackleemeta** [comment]
> 大佬，谢谢你的回复，那个name要从哪拿到呢

name是你的业务内容，你想存什么name就存什么…

**Comment by yjt1216** [comment]
> > 大佬，谢谢你的回复，那个name要从哪拿到呢
> 
> name是你的业务内容，你想存什么name就存什么…
大佬，下载时的地址可不可以自定义呢？

**Comment by jackleemeta** [comment]
> > 大佬，谢谢你的回复，那个name要从哪拿到呢
> 
> name是你的业务内容，你想存什么name就存什么… 大佬，下载时的地址可不可以自定义呢？

不支持的
