### ISSUE TITLE
BackgroundIsolateBinaryMessenger.ensureInitialized

### ISSUE THREAD

**Issue by kentemman** [jackleemeta/al_downloader_flutter#31]
Launching lib/main.dart on Web Server in debug mode...
Waiting for connection from debug service on Web Server...      
/home/.pub-cache/hosted/pub.dev/al_downloader-1.7.4/lib/src/internal/ALDownloaderIsolate.dart:15:38: Error: Member not found: 'BackgroundIsolateBinaryMessenger.ensureInitialized'.
    BackgroundIsolateBinaryMessenger.ensureInitialized(rootIsolateToken);
                                     ^^^^^^^^^^^^^^^^^
Waiting for connection from debug service on Web Server...         38.3s
Failed to compile application

**Comment by jackleemeta** [comment]
al_downloader no support for web
