### ISSUE TITLE
下载apk后不在目标目录，找不到文件了，华为Mate50.

### ISSUE THREAD

**Issue by DevChen** [jackleemeta/al_downloader_flutter#33]
报错信息：I/flutter (22234): ManageExternalStoragePermission: the /storage/emulated/0/Android/data/com.***.***/files/2.1.2.apk file does not exists

**Comment by jackleemeta** [comment]
https://developer.android.com/reference/android/Manifest.permission#MANAGE_EXTERNAL_STORAGE
