### ISSUE TITLE
安卓手机全面屏退出后再次打开就不能下载了，杀死进程后再次打开可以下载

### ISSUE THREAD

**Issue by ShiChenZhi** [jackleemeta/al_downloader_flutter#35]
全面屏退出意思就是处在app的首页，然后滑动屏幕边缘退出当前app，然后再次打开app时，app会重启，但无法下载，一直提示_processDataFromFPort, the function return, because task is not found。

**Comment by ShiChenZhi** [comment]
已经知道问题原因了，IsolateNameServer只有注册流程，没有销毁流程。在启动app的时，又重新注册了一次，因此需要在全面屏退出的方法里移出IsolateNameServer，即执行IsolateNameServer.removePortNameMapping('_kPortForFToAL');就能解决

**Comment by jackleemeta** [comment]
@ShiChenZhi 好的，感谢反馈

**Comment by jackleemeta** [comment]
@ShiChenZhi 修过啦，v1.7.7已发布，thanks
