### ISSUE TITLE
Download folder for Batch downloader

### ISSUE THREAD

**Issue by chavu** [jackleemeta/al_downloader_flutter#41]
How do I set the target download folder for batch download?

**Comment by jackleemeta** [comment]
please see the api https://github.com/jackleemeta/al_downloader_flutter/blob/e5c7b70f1382487279ce5446dcc233535acfddcd/lib/src/ALDownloaderBatcher.dart#L48
https://github.com/jackleemeta/al_downloader_flutter/blob/e5c7b70f1382487279ce5446dcc233535acfddcd/lib/src/chore/ALDownloaderBatcherInputVO.dart#L5

**Comment by chavu** [comment]
Thank you.
