### ISSUE TITLE
How to integrate with flutter_inappwebview?

### ISSUE THREAD

**Issue by mulfa8525** [jackleemeta/al_downloader_flutter#45]
Hello, sir. I'm having trouble integrating al_downloader with flutter_inappwebview. Can you provide a sample for webview?
Thank you in advance, sir!
=====
Check this: https://gist.github.com/pichillilorenzo/ee74e103fdc324f761c5fde7b73bd430

**Comment by jackleemeta** [comment]
Sorry sir, al_downloader no support for web.

**Comment by Shkryabminer** [comment]
//in inappwebview in 
onDownloadStartRequest: (controller, request) async {

all data for dowloading you can get from "request
"
