### ISSUE TITLE
Changing max concurrent number programmatically

### ISSUE THREAD

**Issue by HadiZareZadeh** [jackleemeta/al_downloader_flutter#50]
Is it possible to change the maximum number of concurrent (downloading files) at the same time?

If yes, how?

Else, Is it possible to implement it? How much time will it take?

Thanks in advance.

**Comment by jackleemeta** [comment]
Currently, setting the maximum number of concurrent downloads is supported. But the final maximum number is 7. 

https://github.com/jackleemeta/al_downloader_flutter/blob/fe0e97cc35ea61ce9b5e3e98e8a605ffe9db1480/lib/src/implementation/ALDownloaderIMP.dart#L1733

### Usage

#### iOS
https://github.com/fluttercommunity/flutter_downloader/blob/master/README.md#optional-configuration
![2023-12-26 10 31 05](https://github.com/jackleemeta/al_downloader_flutter/assets/66350348/88fdb880-0fd5-4c40-b0e7-0034dedabc9f)

#### Android
https://github.com/fluttercommunity/flutter_downloader/blob/master/README.md#configure-maximum-number-of-concurrent-download-tasks
![2023-12-26 10 30 12](https://github.com/jackleemeta/al_downloader_flutter/assets/66350348/0f1579cf-317d-4b87-ba6b-015742eb109d)
