### ISSUE TITLE
Changing default directory for both  ALDownloader and ALDownloaderBatcher

### ISSUE THREAD

**Issue by HadiZareZadeh** [jackleemeta/al_downloader_flutter#51]
Where can we define the default directory? I couldn't find anything related to this in the documentation.

**Comment by jackleemeta** [comment]
Setting the directory path is only supported here.

https://github.com/jackleemeta/al_downloader_flutter/blob/fe0e97cc35ea61ce9b5e3e98e8a605ffe9db1480/lib/src/ALDownloader.dart#L56
