### ISSUE TITLE
在下载中杀死app，在重新进入app里，下载框架报ALDownloader | _getALDownloadTaskFromUrl, error = Bad state: No element

### ISSUE THREAD

**Issue by smin9** [jackleemeta/al_downloader_flutter#6]
在下载中杀死app，在重新进入app里，下载框架报ALDownloader | _getALDownloadTaskFromUrl, error = Bad state: No element，

**Comment by smin9** [comment]
如果我杀掉app的进程，在监听到生命周期去调用pause， 好像还是会继续下载。我的是真机  小米9

**Comment by jackleemeta** [comment]
> 如果我杀掉app的进程，在监听到生命周期去调用pause， 好像还是会继续下载。我的是真机 小米9

你好，感谢反馈

升到最新发布的1.4.1版本，1.4.1修复了一波bug，可能会涵盖这个问题的修复

**Comment by smin9** [comment]
好像还是会继续下载，而且调用 var progress = ALDownloader.getDownloadProgressForUrl(model.url);progress 这个值一直是被杀死前的值的。

**Comment by aiqianqianli** [comment]
1.5.0 下载过程中，杀掉进程还是会报ALDownloader | _getTaskFromUrl, error = Bad state: No element

**Comment by jackleemeta** [comment]
> 1.5.0 下载过程中，杀掉进程还是会报ALDownloader | _getTaskFromUrl, error = Bad state: No element

你好，感谢反馈

`ALDownloader | _getTaskFromUrl, error = Bad state: No element`严格来说是一条info，不是error。创建新任务的时候会报。

你可以描述下你遇到的问题表现。比如，新url不能下载、暂停url不能恢复下载、失败url不能恢复下载

**Comment by aiqianqianli** [comment]
> > 1.5.0 下载过程中，杀掉进程还是会报ALDownloader | _getTaskFromUrl,错误 = 坏状态：无元素>> 你好，感谢反馈>> `ALDownloader | _getTaskFromUrl, error = Bad state: No element`严格来说是一条信息，不是错误。创建新任务时会报。>> 你可以描述下你遇到的问题表现。例如，新url不能下载、暂停url不能恢复下载、失败url不能恢复下载
开始下载后，app杀掉进程，再次进入下载页面，进度一直是杀掉进程的进度。此时就下载不了了

**Comment by jackleemeta** [comment]
> 1.5.0 下载过程中，杀掉进程还是会报ALDownloader | _getTaskFromUrl,错误 = 坏状态：无元素>> 你好，感谢反馈>> `ALDownloader | _getTaskFromUrl, error = Bad state: No element`严格来说是一条信息，不是错误。创建新任务时会报。>> 你可以描述下你遇到的问题表现。例如，新url不能下载、暂停url不能恢复下载、失败url不能恢复下载
> 开始下载后，app杀掉进程，再次进入下载页面，进度一直是杀掉进程的进度。此时就下载不了了

是哪个原生端？

**Comment by jackleemeta** [comment]
可能和这个问题一致
issue: [下载失败是什么原因?没有返回错误](https://github.com/jackleemeta/al_downloader_flutter/issues/4)
pr:[on iOS, bug fixed when deleting task concurrently](https://github.com/fluttercommunity/flutter_downloader/pull/637)

原因：在iOS上，原本杀掉进程后会通过[flutter_downloader](https://pub.dev/packages/flutter_downloader) - [FlutterDownloaderPlugin.m](https://github.com/fluttercommunity/flutter_downloader/blob/master/ios/Classes/FlutterDownloaderPlugin.m)的[applicationWillTerminate:]方法把未完成的任务标记为失败，但[applicationWillTerminate:]中的代码存在数据竞争风险，导致标记失败了

我这边稍后会给flutter_downloader提pr继续解决类似的问题

临时解决方案：本地把[FlutterDownloaderPlugin.m](https://github.com/fluttercommunity/flutter_downloader/blob/master/ios/Classes/FlutterDownloaderPlugin.m)的[applicationWillTerminate:]实现改成这样：
```
- (void)applicationWillTerminate:(nonnull UIApplication *)application
{
    if (debug) {
        NSLog(@"applicationWillTerminate:");
    }
    for (NSString* key in _runningTaskById) {
        if ([_runningTaskById[key][KEY_STATUS] intValue] < STATUS_COMPLETE) {
            __typeof__(self) __weak weakSelf = self;
            dispatch_sync(databaseQueue, ^{
                [weakSelf updateTask:key status:STATUS_CANCELED progress:-1];
            });
        }
    }
    _session = nil;
    _mainChannel = nil;
    _dbManager = nil;
    databaseQueue = nil;
    _runningTaskById = nil;
}
```

**Comment by jackleemeta** [comment]
这个问题v1.5.6已解决

如果还有其他问题，可以随时打开这个issue
