### ISSUE TITLE
where will be the video saved?

### ISSUE THREAD

**Issue by chh0871** [jackleemeta/al_downloader_flutter#8]
I am trying to find the video in the device.. can we get the path where it is being stored..

terminal:
I/flutter (23501): ALDownloader | try to download downloadtaskOfUrl = https://fb.watch/dE4OowMCmI/, url is complete
I/flutter (23501): ALDownloader | download progress = 1.0, url = https://fb.watch/dE4OowMCmI/
I/flutter (23501):
I/flutter (23501): ALDownloader | download succeeded, url = https://fb.watch/dE4OowMCmI/

**Comment by jackleemeta** [comment]
Hi, thanks for your question.

Call [ALDownloaderPersistentFileManager.getAbsolutePhysicalPathOfFileForUrl] to get the stored path.

In addition, upgrading to the latest version 1.5.6 is recommended.

**Comment by chh0871** [comment]
i am using my cell phone as an emulator ..
and this path is not there.. 

getAbsoluteVirtualPathOfFileWithUrl | filePath = /storage/emulated/0/Android/data/com.example.viddownloader/files/al_flutter/al_unknown/b52e63742536902faf1e28b82bebdff6

**Comment by jackleemeta** [comment]
> i am using my cell phone as an emulator .. and this path is not there..
> 
> getAbsoluteVirtualPathOfFileWithUrl | filePath = /storage/emulated/0/Android/data/com.example.viddownloader/files/al_flutter/al_unknown/b52e63742536902faf1e28b82bebdff6

Have you upgraded to 1.5.6?

**Comment by chh0871** [comment]
yup

**Comment by jackleemeta** [comment]
> yup

ur resource content type is text/html, not video.

<img width="764" alt="pic" src="https://user-images.githubusercontent.com/66350348/173738912-86811ca5-988b-4432-9ce1-5fa6e881303c.png">

It will be stored as html here.

<img width="1051" alt="pic1" src="https://user-images.githubusercontent.com/66350348/173739400-495b8b9f-5573-4e62-8905-51b50c02be2f.png">

**Comment by chh0871** [comment]
it was a fb video link..

**Comment by jackleemeta** [comment]
al_downloader can't parse html document. I thought you might need a tool like this.

- [youtube_downloader](https://pub.dev/packages/youtube_downloader)
- [facebook_video_download](https://pub.dev/packages/facebook_video_download)

**Comment by chh0871** [comment]
ok  i will check that thanks
