### ISSUE TITLE
应当有排队状态

### ISSUE THREAD

**Issue by jsleishen** [jackleemeta/al_downloader_flutter#9]
有下载任务数限制,应当有排队状态

**Comment by jackleemeta** [comment]
你好 @jsleishen ， 感谢建议。

对排队状态的处理，是我这边一直在考虑的问题。

理论上，下载这种业务是一定会存在对对的，同时包设计的初衷是尽量简化状态并且在逻辑上保持通顺。

在al_downloader 1.6.5之前的版本，对于排队的状态处理较模糊。

1.6.5之后做了这样的处理：`如果任务正在排队，视为正在下载中但进度为0`。详见这个[commit](https://github.com/jackleemeta/al_downloader_flutter/commit/da0a3c2aab72f375106e54e0298efd967d9dd7ce)。
这时候可以像真正的正在下载中的任务一样对排队中的任务进行操作（例如暂停操作）。
